profiles:
  active: simple
spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite::../../document/sql/document.db
    username:
    password:
    hikari:
      connection-timeout: 3000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #        不使用nacos的配置中心配置覆盖本地配置
        enabled: false # 这个东西特别坑，设置成false才能避免项目启动慢（nacos服务没有启动的时候
        #        不把自己注册到注册中心的地址
        register-enabled: false
        heart-beat-timeout: 3000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数（负值代表没有限制
          max-wait: 3000 # 连接池最大阻塞等待时间
          min-idle: 0 # 连接池中最小空闲连接
          max-idle: 8 # 连接池中最大空闲连接
      timeout: 3000 # 读取超时
      connect-timeout: 3000 #连接超时
management:
  health:
    defaults:
      enabled: false # 反正三方服务都没有启动，监控也没啥意义
