server:
  port: 1514
spring:
  profiles:
    active: test
  application:
    name: icboluo-note
mybatis:
  configuration:
    #    自动小驼峰映射
    map-underscore-to-camel-case: true
  #    为什么这里指定 mybatis/*Mapper.xml不行（文件夹也改了
  mapper-locations: mapper/*Mapper.xml
logging:
  level:
    #    level 后面直接跟日志级别会启动报错
    com.icboluo: debug
read-excel-entity:
  excel-path: icboluo-note/database.xlsx
  general-sql-path: icboluo-note/creat.sql
  sheet-name:
write-excel-entity:
  excel-path: database.xlsx
  database: note
  table-name:

