profiles:
  active: simple
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: note_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #          uri: http://localhost:8001
          uri: lb://note #动态创建路由的方式
          predicates:
            - Path=/note/get/** # 断言，路径相匹配的进行路由
              #- After=2017-01-20T17:42:47.789-07:00[America/Denver] 这个时间以后可以访问
              #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]  这个时间以前可以访问
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.icboluo.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
            # 过滤,学这个东西不如自己写配置感觉
            #filters:
            #  - AddRequestHeader=X-Request-red, blue
        - id: note_route2
          uri: http://localhost:8001
          #        uri: lb://note
          predicates:
            - Path=/note/lb/** #断言,路径相匹配的进行路由
  redis:
    host: 127.0.0.1
    port: 6379
