server:
  port: 1110
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # 这里如果为create，每次都要重新创建表；如果是update，表若存在则不重建
  profiles:
    active: simple
  application:
    name: icboluo-sql
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    com.icboluo: debug
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:dd日 HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
mybatis-plus:
  configuration:
    #    自动小驼峰映射
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
