server:
  port: 1110
spring:
  application:
    name: icboluo-sql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/note?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    com.icboluo: debug
mybatis:
  configuration:
    #    自动小驼峰映射
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
