profiles:
  active: simple
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
        enabled: false
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite::../../document/sql/sqlite3.db
    username:
    password:
