spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
        enabled: false
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite::../../document/sql/document.db
    username:
    password:
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
    datasource: derby  # 或者h2 ，可以使用这2种嵌入式数据库替换sqlite驱动，实测都不太行，感觉需要手写
